#!/bin/bash
wget https://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.15-1_all.deb

#Update packages and install server, shell and router
sudo apt-get update
sudo apt-get install mysql-server mysql-shell mysql-router -y

#Update mysql.cnf
sudo bash -c 'echo "bind-address  = 0.0.0.0" >> /etc/mysql/mysql.conf.d/mysqld.cnf'
sudo systemctl start mysql
sudo mysql_secure_installation

#Add Replication User
no_pass=0
while [ $no_pass -eq 0 ]
do
   read -p "Enter Replication Password: " pass
   read -p "Please Enter Password Again: " pass2 
   if [ $pass != $pass2 ]
   then
     print "Passwords do not match. Try again"
   else
     no_pass=1
   fi
done

print ""
print "Next password prompt is a ROOT prompt"
mysql -u root -p <<EOF
create user 'replUser' identified by '${pass}';
grant all privileges on *.* to 'replUser'@'%' with grant option;
reset master;
EOF
